#!/bin/sh
Root="${ROOT-/www/snoot.club}"
Skeleton_Snoot="$Root/skeleton"
Snoot_Root="$Root/snoots"
Snoot="$1"
lspf="$Root/last_snoot_port"
Last_Snoot_port="$(if [ -e $lspf ]; then cat $lspf; else echo -n 33110; fi)"
Ssh_Port="$(($Last_Snoot_port + 1))"
Web_Port="$(($Ssh_Port + 1))"

echo enter their ssh key pls:
read -r Public_Key

cd "$Snoot_Root"

rsync -av "$Skeleton_Snoot/" "$Snoot/"

cd "$Snoot/application"

>package.json cat <<packagejson
{
  "name": "application",
  "version": "1.0.0",
  "main": "index.js",
  "module": "main.js",
  "scripts": {
    "start": "micro -l tcp://0.0.0.0:${PORT-80}",
    "start:developer": "micro -l tcp://0.0.0.0:${PORT-80}"
  },
  "author": "$Snoot <$Snoot@snoot.club>",
  "license": "MPL-2.0",
  "description": ""
}
packagejson

npm install micro serve-handler

>authorized_keys echo $Public_Key

>website/index.html cat <<indexhtml
<!doctype html>
<marquee direction=down behavior=alternate>
  <marquee direction=right behavior=alternate>
    <pre>
      welcome to $Snoot's homepage

      if you are $Snoot, then you have two choices:
        • your ssh port is $Ssh_Port.
          - <code>ssh root@snoot.club -p $Ssh_Port</code>
          - the files for the application are in <code>/application</code>.
        • your sftp user is $Snoot.
          - <code>sftp $Snoot@snoot.club</code>
          - the files for the website are in <code>./website</code>
    </pre>
  </marquee>
</marquee>
indexhtml

cd ..

>docker-compose.yml cat <<dockercomposeyml
version: "3"
services:
  node:
    image: "node:latest"
    working_dir: /application
    environment:
      - NODE_ENV=production
    volumes:
      - ./application/:/application
    ports:
      - "$((Ssh_Port)):22"
      - "$((Web_Port)):80"
    restart: always
    command: "/application/.start.sh"
dockercomposeyml

docker-compose up -d

>nginx.conf cat <<nginxconf
server {
  include $Root/blocks/error_page.nginx;

  default_type text/plain;

  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name $Snoot.x.x;
  access_log $Snoot_Root/$Snoot/logs/access.ssl.log;
  error_log $Snoot_Root/$Snoot/logs/error.ssl.log;

  ssl on;
  ssl_certificate      /usr/chee/certs/x.x.pem;
  ssl_certificate_key  /usr/chee/certs/x.x.key;

  location / {
    proxy_pass http://127.0.0.1:$Web_Port/;
    proxy_set_header Host \$http_host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    client_max_body_size 100m;
  }
}

server {
  listen 80;
  listen [::]:80;
  server_name $Snoot.x.x;
  return 301 https://$Snoot.x.x/\$request_uri;
}
nginxconf

echo $Web_Port > "$Root/$lspf"

nginx
