#!/bin/sh
export PATH=".:$PATH"
Snoot="$1"
Snoot_Root="/www/snoot.club/snoots"

cd "$Snoot_Root"

Existing_User="$(</etc/passwd awk -F: '{print $1}' | grep -e "^$Snoot\$")"

if [ -z "$Existing_User" ]; then
	say creating user

	sudo useradd -m -d "/snoots/$Snoot" -g common -G common,undercommon -s /bin/nologin "$Snoot"
else

fi

echo enter their ssh key pls:

read -r Public_Key



sudo mkdir -p "/snoots/$Snoot/.ssh"
sudo sh -c "echo $Public_Key >> /snoots/$Snoot/.ssh/authorized_keys"
sudo chmod -R 755 "/snoots/$Snoot/.ssh"
sudo chown -R root.root "/snoots/$Snoot/.ssh"



/www/snoot.club/contain_snoot "$Snoot" "$Public_Key"

sudo chown -R "$Snoot.common" "$Snoot_Root/$Snoot/application/website"



/www/snoot.club/bind_snoots



sudo nginx -s reload
